#!/bin/bash
# Extract ABIs from compiled contracts for frontend integration
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

CONTRACTS_DIR="$ROOT_DIR/packages/contracts/out"
OUTPUT_DIR="$ROOT_DIR/packages/sdk/src/abis"

echo "🔧 CastQuest V3 ABI Extraction"
echo "==============================="
echo ""
echo "Contracts directory: $CONTRACTS_DIR"
echo "Output directory: $OUTPUT_DIR"
echo ""

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Check if contracts are compiled
if [ ! -d "$CONTRACTS_DIR" ]; then
    echo "❌ Contracts not compiled. Running forge build..."
    cd "$ROOT_DIR/packages/contracts"
    forge build || {
        echo "❌ Build failed"
        exit 1
    }
fi

# List of contracts to extract
contracts=(
    "CASTToken"
    "MediaToken"
    "MediaTokenFactory"
    "MediaRegistry"
    "MediaMarket"
    "FeeRouter"
    "FeeManagerV3"
    "Marketplace"
    "QuestToken"
    "GameToken"
    "CodeToken"
    "SponsorToken"
    "GovernanceV2"
)

echo "📦 Extracting ABIs..."
echo ""

extracted=0
failed=0

for contract in "${contracts[@]}"; do
    # Find the contract JSON file
    contract_json=$(find "$CONTRACTS_DIR" -name "${contract}.json" | head -1)
    
    if [ -z "$contract_json" ]; then
        echo "⚠️  Warning: ${contract}.json not found, skipping..."
        ((failed++))
        continue
    fi
    
    # Extract ABI using jq
    if command -v jq >/dev/null 2>&1; then
        jq '.abi' "$contract_json" > "$OUTPUT_DIR/${contract}.json"
        echo "  ✅ Exported ${contract}.json"
        ((extracted++))
    else
        echo "❌ Error: jq not installed. Please install jq to extract ABIs."
        exit 1
    fi
done

echo ""
echo "📊 Summary:"
echo "  Extracted: $extracted ABIs"
echo "  Failed: $failed ABIs"
echo ""

# Generate TypeScript types index file
echo "📝 Generating TypeScript index..."

cat > "$OUTPUT_DIR/index.ts" << 'EOF'
/**
 * CastQuest V3 Contract ABIs
 * Auto-generated by extract-abis.sh
 */

// Core Tokens
import CASTTokenABI from './CASTToken.json';
import MediaTokenABI from './MediaToken.json';
import SponsorTokenABI from './SponsorToken.json';

// Quest/Game/Code
import QuestTokenABI from './QuestToken.json';
import GameTokenABI from './GameToken.json';
import CodeTokenABI from './CodeToken.json';

// Infrastructure
import MediaRegistryABI from './MediaRegistry.json';
import MediaTokenFactoryABI from './MediaTokenFactory.json';

// Fee Management
import FeeRouterABI from './FeeRouter.json';
import FeeManagerV3ABI from './FeeManagerV3.json';

// Markets
import MediaMarketABI from './MediaMarket.json';
import MarketplaceABI from './Marketplace.json';

// Governance
import GovernanceV2ABI from './GovernanceV2.json';

export {
  // Core Tokens
  CASTTokenABI,
  MediaTokenABI,
  SponsorTokenABI,
  
  // Quest/Game/Code
  QuestTokenABI,
  GameTokenABI,
  CodeTokenABI,
  
  // Infrastructure
  MediaRegistryABI,
  MediaTokenFactoryABI,
  
  // Fee Management
  FeeRouterABI,
  FeeManagerV3ABI,
  
  // Markets
  MediaMarketABI,
  MarketplaceABI,
  
  // Governance
  GovernanceV2ABI,
};

// Type exports for TypeScript
export type { Abi } from 'viem';
EOF

echo "  ✅ Created index.ts"
echo ""

# Check if wagmi is installed and generate types
if [ -f "$ROOT_DIR/package.json" ] && grep -q "@wagmi/cli" "$ROOT_DIR/package.json"; then
    echo "🔧 Generating TypeScript types with wagmi..."
    cd "$ROOT_DIR"
    
    # Check if wagmi.config.ts exists
    if [ -f "wagmi.config.ts" ]; then
        pnpm wagmi generate || {
            echo "⚠️  Warning: wagmi generate failed, but ABIs were extracted successfully"
        }
    else
        echo "ℹ️  No wagmi.config.ts found, skipping type generation"
    fi
else
    echo "ℹ️  wagmi not installed, skipping type generation"
fi

echo ""
echo "✅ ABI Extraction Complete!"
echo ""
echo "📁 Files created:"
echo "  $OUTPUT_DIR/*.json"
echo "  $OUTPUT_DIR/index.ts"
echo ""
echo "Next Steps:"
echo "1. Import ABIs in your frontend: import { FeeManagerV3ABI } from '@castquest/sdk/abis'"
echo "2. Use with viem/wagmi: useReadContract({ abi: FeeManagerV3ABI, ... })"
echo "3. Update contract addresses in SDK configuration"
echo ""
